### ISSUE TITLE
Setting up moment as a shared dependency fails

### ISSUE THREAD

**Issue by TheMcMurder** [react-microfrontends/navbar#4] opened 2020-03-11 20:04 UTC
run: 
`localStorage.setItem('import-map-override:moment', 'https://cdn.jsdelivr.net/npm/moment@2.24.0/moment.min.js')` in the console while on this page https://react.microfrontends.app/

And run [this](https://github.com/react-microfrontends/navbar/tree/moment) branch locally with an override to see the error.

**Comment by internettrans** [comment] 2020-03-14 04:15
This is caused by the same problem described in https://github.com/react-microfrontends/api/issues/1. It is fixed in https://github.com/webpack/webpack/pull/10503, which will be published in the next webpack@5 beta.

In the meantime you can work around it with an ad hoc systemjs extra (see [this commit](https://github.com/react-microfrontends/root-config/commit/fb664b2c59a30bedaf185854d509f776306440ae), https://github.com/react-microfrontends/api/issues/1#issuecomment-594289086, and [this code sandbox](https://codesandbox.io/s/gallant-chaplygin-fsjnf))

**Closed as completed by internettrans** 2020-03-14 04:15 UTC
